[tool.bumpversion]
current_version = "1.0.0"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
# search = "{current_version}"
# replace = "{new_version}"
commit = true
tag = false
allow_dirty = false
message = "Bump version: {current_version} → {new_version}"
commit_args = ""

[[tool.bumpversion.files]]
filename = "Dockerfile"
search = "ENV VERSION={current_version}"
replace = "ENV VERSION={new_version}"
